### PR TITLE
Upgraded to Angular 8

### PR DESCRIPTION
**Pull request by micobarac**
Upgraded to Angular 8

### CODE REVIEW

**Comment by DenysVuika** [comment]
The PR was made with Yarn? Was thinking to switch to the Yarn within Travis setup, can do that easily

**Comment by micobarac** [comment]
https://update.angular.io/#7.0:8.0

For Angular 8 to work properly, make sure you are using Node 10 or later.

**Comment by micobarac** [comment]
Yarn version is also pretty old in Travis configuration.

The latest Yarn version is 1.16.0.

**Comment by DenysVuika** [comment]
Thanks for your contribution, @micobarac

**Pull request merged**
